### PR TITLE
paru in the readme

### PR DESCRIPTION
**Pull request by lollilol**
replace yay with paru

### CODE REVIEW

**Comment by zzag** [comment]
Can you provide some reasoning behind this change?

**Comment by lollilol** [comment]
first rust, but: more recent release, less issues, more pull requests/contributors.

**Comment by zzag** [comment]
> first rust

While Rust is indeed a good programming language to consider writing your project in, just because something is written in Rust doesn't mean it's better. There would be fewer memory safety related issues, sure, but on the other hand Go doesn't have terrible memory safety issues like C or C++ either.

---

yay was provided as an example because it's yaourt of these days, From what I can tell, it's still maintained, it's not so active nowadays though, but it's also a quite mature project. Given the number of AUR helpers, I'm not sure about this change to be frank.

**Comment by lollilol** [comment]
i guess you're right. They are more ore less the same:
https://github.com/Morganamilo/paru/pulse/monthly
https://github.com/Jguer/yay/pulse/monthly

i have the feeling yay is more popular, but i think paru is catching up

**Pull request closed without merging**
